### ISSUE TITLE
Worldgen Lag and Console Spam due to setBlock in distant chunks

### ISSUE THREAD

**Issue by Derpford** [Apothicon02/Create-Molten-Geodes#2]
Whenever I wander far enough to cause chunks to be generated, I start getting excessive console spam along the lines of this:
```
Detected setBlock in a far chunk [-16, 22], pos: MutableBlockPos{x=-241, y=-18, z=366}, status: minecraft:features, currently generating: Placed Reference{ResourceKey[minecraft:worldgen/configured_feature / molten_geodes:brass_geode]=Configured: com.Apothic0n.MoltenGeodes.api.biome.features.types.MoltenGeodeFeature@55aa5918: net.minecraft.world.level.levelgen.feature.configurations.GeodeConfiguration@534b7546}
```

This also causes a pretty large lagspike. This also occurs with Molten Vents, near as I can tell, but I could only find log entries for Molten Geodes.

**Comment by DadoIrie** [comment]
same here on forge 43.2.4 1.19.2

**Comment by Apothicon02** [comment]
This does not occur on Molten Vents, the only reason it occurs in Molten Geodes is because their wide. The console spam is something I chose to have because the alternative requires compromising by making the geodes smaller. This shouldn't cause any notable lag unless you have the geodes set to generate very commonly. 
Solution: Set the geodes to generate less if its too laggy and ignore the console spam OR switch to molten vents which has neither of these issues due to the small horizontal size of the features in that mod.
